% SUBSTR - has been generated by OCT2MAT for providing compatibility with Octave functions
function y = substr(s,i,j)
  if i<0, i=length(s)+i+1; end;
  if nargin<3, y = s(i:end);
  else y = s(i:i+j-1); end