% VEC - has been generated by OCT2MAT for providing compatibility with Octave functions
function x = vec(x,i)
  if nargin<==1, x = x(:); elseif nargin==2, x=x(i); else error('vec has invalid number of arguments'); end;
